#Configurations for UAT's environment

version = 0.1
[default]
[prod.default]
[default.deploy.parameters]
stack_name = "todo-sam-app-UAT"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1u6en114133fr"
s3_prefix = "todo-sam-app-UAT"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
